parameters:
  twig.config:
    debug: false
    auto_reload: false
    cache: true

  cors.config:
    enabled: true
    allowedHeaders:
      - 'Content-Type'
      - 'Authorization'
      - 'X-Requested-With'
      - 'Accept'
      - 'Origin'
    allowedMethods:
      - 'GET'
      - 'POST'
      - 'PUT'
      - 'PATCH'
      - 'DELETE'
      - 'OPTIONS'
    allowedOrigins:
      - 'https://i5l.95d.mytemp.website'
    allowedOriginsPatterns: []
    exposedHeaders: false
    maxAge: 1000
    supportsCredentials: true


