_core:
  default_config_hash: 68A3PDsSIoX2q7iFOa2lMdnYkgKgem4uh1_RBxcRVWU
report-only:
  enable: false
  directives:
    object-src:
      base: none
    script-src:
      base: self
      flags:
        - report-sample
        - inline-speculation-rules
        - unsafe-hashes
        - unsafe-inline
        - unsafe-eval
        - wasm-unsafe-eval
    style-src:
      base: self
      flags:
        - report-sample
    webrtc: block
    worker-src:
      base: self
    base-uri:
      base: self
    form-action:
      base: self
    frame-ancestors:
      base: self
  reporting:
    plugin: none
enforce:
  enable: true
  directives:
    object-src:
      base: none
    script-src:
      base: self
    style-src:
      base: self
      flags:
        - unsafe-inline
    base-uri:
      base: self
    default-src:
      base: self
    img-src:
      base: self
  reporting:
    plugin: none
