_core:
  default_config_hash: O3rsbjEveBvnof1Hdq3ih8UBqlRN2betEk9OZhaiTPM
tac_lite_categories:
  business_cat: business_cat
  contract_unit: contract_unit
  directors_category: directors_category
  energy_bill_type_and_category: energy_bill_type_and_category
tac_lite_schemes: '1'
menu_rebuild_needed: true
tac_lite_config_scheme_1:
  name: test
  perms:
    grant_view: grant_view
    grant_update: grant_update
    grant_delete: grant_delete
  unpublished: 1
  term_visibility: 1
  tac_lite_create: 1
tac_lite_grants_scheme_1:
  anonymous:
    business_cat: {  }
  authenticated:
    business_cat: {  }
  content_editor:
    business_cat:
      5: '5'
  administrator:
    business_cat: {  }
  hydro:
    business_cat:
      5: '5'
