build:
  desktop:
    values:
      cells:
        -
          title: 'अध्यक्ष एवं प्रबंध निदेशक'
        -
          title: 'निदेशक (परियोजनाएं)'
        -
          title: 'निदेशक (कार्मिक)'
        -
          title: 'मुख्य सतर्कता अधिकारी'
        -
          title: 'निदेशक (वित्त)'
        -
          title: 'निगमित कार्य'
        -
          title: 'सहायक कंपनियां और संयुक्त उद्यम'
        -
          title: परियोजनाएं
        -
          title: 'निगमित कार्य'
        -
          title: निर्माणाधीन
        -
          title: प्रचालनाधीन
        -
          title: 'बीडीई विभाग निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'निगमित योजना निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'निर्माण पूर्व'
        -
          title: 'एसजेवीएन अरुण-3 पावर देव. कंपनी (एसएपीडीसी) 900 मेगावाट'
        -
          title: 'उप मुख्य सतर्कता अधिकारी'
        -
          title: 'निगमित वित्त एवं लेखा निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'विभागाध्यक्ष निगमित मानव संसाधन निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'विभागाध्यक्ष सीएम एंड सी निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'दिल्ली वित्त निगमित मुख्यालय'
          subtitle: दिल्ली
        -
          title: 'कंपनी सचिव निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'विभागाध्यक्ष आंतरिक लेखा परीक्षा निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'वाणिज्यिक एवं प्रणाली संचालन निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'सिविल संविदा निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'संपर्क कार्यालय निगमित मुख्यालय'
          subtitle: दिल्ली
        -
          title: 'खिरवीरे डब्ल्यूपीएस 47.6 मेगावाट महाराष्ट्र'
          subtitle: प्रचालनाधीन
        -
          title: 'एसजेवीएन ग्रीन एनर्जी लिमिटेड (एसजीईएल)'
          subtitle: '[पूर्ण स्वामित्व वाली सहायक कंपनी]'
        -
          title: 'सूचना प्रौद्योगिकी निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'विद्युत संविदा निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'एसजेवीएन लोअर अरुण पावर डेवलपमेंट कंपनी (एसएलपीडीसी) 669 मेगावाट'
        -
          title: 'एसजेवीएन एसपीपी 900 मेगावाट'
          subtitle: गुजरात
        -
          title: 'चरणका एसपीएस 5.6 मेगावाट गुजरात'
          subtitle: प्रचालनाधीन
        -
          title: 'सदला डब्ल्यूपीएस 50 मेगावाट गुजरात'
          subtitle: प्रचालनाधीन
        -
          title: 'क्रॉस बॉर्डर पावर ट्रांसमिशन कंपनी (सीपीटीसी) संयुक्त उद्यम'
        -
          title: 'असम रिन्यूएबल एनर्जी लिमिटेड (सारेल)'
        -
          title: 'एसजेवीएन थर्मल प्राइवेट लिमिटेड (एसटीपीएल) 1320 मेगावाट'
        -
          title: 'विद्युत संविदा निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'विद्युत डिजाइन निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'नाथपा झाकड़ी एचपीएस 1500 मेगावाट हिमाचल प्रदेश'
          subtitle: प्रचालनाधीन
        -
          title: 'धौलासिद्ध एचईपी 66 मेगावाट हिमाचल प्रदेश'
          subtitle: निर्माणाधीन
        -
          title: 'एटलिन एचईपी 3097 मेगावाट अरुणाचल प्रदेश'
          subtitle: 'निर्माण पूर्व'
        -
          title: 'एचएम डिजाइन निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'सिविल डिजाइन निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'व्यवसाय विकास विस्तार निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'रूफ टॉप सोलर निगमित मुख्यालय'
          subtitle: दिल्ली
        -
          title: 'वास्तुकला निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'निगमित सुविधा प्रबंधन विभाग निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'आरईआईए निगमित मुख्यालय'
          subtitle: दिल्ली
        -
          title: 'पावर ट्रेडिंग एवं बीडीई निगमित मुख्यालय'
          subtitle: दिल्ली
        -
          title: 'गुणवत्ता आश्वासन एवं निरीक्षण निगमित मुख्यालय'
          subtitle: शिमला
        -
          title: 'सुन्नी बांध एचईपी 382 मेगावाट हिमाचल प्रदेश'
          subtitle: निर्माणाधीन
        -
          title: 'लुहरी एचईपी चरण-1 210 मेगावाट हिमाचल प्रदेश'
          subtitle: निर्माणाधीन
        -
          title: 'नैटवाड़ मोरी एचपीएस 60 मेगावाट उत्तराखंड'
          subtitle: प्रचालनाधीन
        -
          title: 'रामपुर एचपीएस 412 मेगावाट हिमाचल प्रदेश'
          subtitle: प्रचालनाधीन
        -
          title: 'चिनाब एचईपी हिमाचल प्रदेश'
          subtitle: 'निर्माण पूर्व'
        -
          title: 'जखोल सांकरी एवं देवसारी एचईपी उत्तराखंड'
          subtitle: 'निर्माण पूर्व'
        -
          title: 'एमिनी/अमुलिन मिहोमडोम एचईपी अरुणाचल प्रदेश'
          subtitle: 'निर्माण पूर्व'
        -
          title: 'अतुन्ली एचईपी 680 मेगावाट अरुणाचल प्रदेश'
          subtitle: 'निर्माण पूर्व'
