display:
  default:
    display_options:
      footer:
        area:
          content:
            value: '<div class="about-see-more"><a class="see-more-btn" href="/sjvn/hi/kanpanai-kaa-paraicaya">और देखें</a></div>'
            format: full_html
