display:
  default:
    display_title: डीफॉल्ट
    display_options:
      title: मीडिया
      filters:
        status:
          group_info:
            label: प्रकाशित
            group_items:
              1:
                title: प्रकाशित
              2:
                title: अप्रकाशित
        name:
          expose:
            label: नाम
  page:
    display_title: पृष्ठ
    display_options:
      fields:
        edit_media:
          text: 'संपादित करें'
        delete_media:
          text: मिटायें
  widget:
    display_options:
      filters:
        name:
          expose:
            label: नाम
  widget_table:
    display_options:
      fields:
        name:
          label: नाम
      filters:
        name:
          expose:
            label: नाम
