display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        title:
          label: शीर्षक
        status:
          label: अवस्था
          settings:
            format_custom_false: अप्रकाशित
            format_custom_true: प्रकाशित
        operations:
          label: कार्यवाही
      pager:
        options:
          tags:
            next: 'अगला ›'
            previous: '‹ पिछला'
      filters:
        title:
          expose:
            label: शीर्षक
        status:
          expose:
            label: अवस्था
          group_info:
            group_items:
              1:
                title: प्रकाशित
              2:
                title: अप्रकाशित
  page_1:
    display_title: पृष्ठ
