display:
  block_2:
    display_options:
      footer:
        area:
          content:
            value: '<p><a class="see-more-btn" href="/sjvn/hi/press-release">और देखें</a></p>'
            format: full_html
  block_3:
    display_options:
      footer:
        area:
          content:
            value: '<p><a class="see-more-btn" href="/sjvn/en/alert-archive">और देखें</a></p>'
            format: full_html
  default:
    display_options:
      title: "प्रेस विज्ञप्ति\r\n"
label: 'प्रेस विज्ञप्ति'
