display:
  block_1:
    display_options:
      header:
        area:
          content:
            value: '<div class="container"><div class="row"><div class="col-sm-6"><img src="/sjvn/themes/sjvn/images/about_img.jpg" alt="Banner" width="525" height="263"></div><div class="col-sm-6"><p>एसजेवीएन लिमिटेड विद्युत मंत्रालय के नियंत्रणाधीन एक नवरत्न सार्वजनिक क्षेत्र का उपक्रम है जिसकी स्थापना 24 मई,1988 को भारत सरकार तथा हिमाचल प्रदेश सरकार के संयुक्त उपक्रम के रूप में की गई थी । एसजेवीएन अब एक सूचीबद्ध कंपनी है जिसमें उसके शेयरहोल्डर पैटर्न के तहत भारत सरकार, हिमाचल प्रदेश सरकार एवं जनता का क्रमशः 55.00% , 26.85% एवं 18.15% का इक्विटी अंशदान शामिल है । एसजेवीएन की मौजूदा भुगतान की गई पूंजी तथा अधिकृत शेयर पूंजी क्रमशः 3929.80 करोड़ तथा 7000 करोड़ रूपए है । एसजेवीएन की कुल पूंजी दिनांक 31.03.2025 को 14189.26 करोड़ रूपए है ।</p><p>एक परियोजना और एक राज्य (यानी हिमाचल प्रदेश में भारत के सबसे बड़े 1500 मेगावाट नाथपा झाकड़ी हाइड्रो पावर स्टेशन) से शुरुआत करते हुए, कंपनी ने कुल 3096.60 मेगावाट की स्थापित क्षमता तथा 123 किमी ट्रांसमिशन लाइन समेत कुल चौदह परियोजनाओं की कमीशनिंग कर ली है । एसजेवीएन वर्तमान में भारत के पड़ोसी देश जैसे नेपाल के अलावा भारत में हिमाचल प्रदेश, उत्तराखण्ड, बिहार, महाराष्ट्र, उत्तर प्रदेश, पंजाब, अरुणाचल प्रदेश, गुजरात, राजस्थान, असम, मिजोरम, मध्य प्रदेश, कर्नाटक तथा छत्तीसगढ़ में विद्युत परियोजनाओं का निष्पादन कर रहा है ।</p></div></div></div>'
            format: full_html
  default:
    display_options:
      title: ''
label: ''
