display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        title:
          label: शीर्षक
        status:
          label: अवस्था
        operations:
          label: कार्यवाही
      pager:
        options:
          tags:
            next: 'अगला ›'
            previous: '‹ पिछला'
      filters:
        title:
          expose:
            label: शीर्षक
        status:
          expose:
            label: अवस्था
  page_1:
    display_title: पृष्ठ
