label: मीडिया
display:
  default:
    display_title: डीफॉल्ट
    display_options:
      title: मीडिया
      fields:
        status:
          label: अवस्था
          settings:
            format_custom_false: अप्रकाशित
            format_custom_true: प्रकाशित
        operations:
          label: कार्यवाही
      pager:
        options:
          tags:
            next: 'अगला ›'
            previous: '‹ पिछला'
      filters:
        status:
          group_info:
            group_items:
              1:
                title: प्रकाशित
              2:
                title: अप्रकाशित
  media_page_list:
    display_title: मीडिया
    display_options:
      menu:
        title: मीडिया
