display:
  default:
    display_options:
      title: "निगमित प्रशासन\r\n"
  page_10:
    display_options:
      title: 'सहायक कंपनियों के वित्तीय विवरण'
  page_2:
    display_options:
      title: "शेयर होल्डिंग पैटर्न\r\n"
  page_3:
    display_options:
      title: "कॉर्पोरेट घोषणाएँ\r\n"
  page_4:
    display_options:
      title: प्रतिलिपि
  page_5:
    display_options:
      title: "त्रैमासिक / चालू वर्ष रिजल्ट\r\n"
  page_6:
    display_options:
      title: "आईईपीएफ विवरण\r\n"
      footer:
        area:
          content:
            value: '<div class="iepf-wrapper"><div class="iepf-intro"><p class="iepf-title">निवेशक शिक्षा एवं संरक्षण कोष (आईईपीएफ) से अदत्तल राशि/शेयरों का दावा करने के लिए प्राधिकरण को आवेदन प्रपत्र आईईपीएफ-5 में फाईल किया जाएगा जो निम्न्लिखित लिंक पर उपलब्धल हैः</p><p><a class="iepf-link" href="http://www.iepf.gov.in/IEPF/corporates.html">http://www.iepf.gov.in/IEPF/corporates.html&nbsp;</a></p></div><div class="iepf-grid"><div class="iepf-card"><h3>आईईपीएफ प्राधिकरण के लिए नोडल अधिकारी</h3><p><strong>श्री सोमेन्द्र दास, Das</strong></p><p>कंपनी सचिव, एसजेवीएन लिमिटेड,</p><p>शक्ति सदन, एसजेवीएन कारपोरेट कार्यालय परिसर,</p><p>शनान,शिमला-171006, हिमाचल प्रदेश,</p><p>दूरभाष. +91 177 2660075</p><p>फैक्स.+91 177 2660071</p><p>ई-मेल investor[dot]relations[at]sjvn[dot]nic[dot]in</p></div><div class="iepf-card"><h3>आईईपीएफ प्राधिकरण के लिए उप नोडल अधिकारी</h3><p><strong>Mr श्री अरुण कुमार शर्मा</strong></p><p>प्रबंधक, एसजेवीएन लिमिटेड</p><p>शक्ति सदन, एसजेवीएन कारपोरेट कार्यालय परिसर,</p><p>शनान,शिमला-171006, हिमाचल प्रदेश,</p><p>दूरभाष. +91 177 2660075</p><p>फैक्स.+91 177 2660071</p><p>ई-मेल: investor[dot]relations[at]sjvn[dot]nic[dot]in</p></div></div></div>'
            format: full_html
  page_7:
    display_options:
      title: "एजीएम के दौरान सीएमडी भाषण\r\n"
  page_8:
    display_options:
      title: 'वार्षिक रिपोर्ट'
  page_9:
    display_options:
      title: ' वार्षिक विवरणी '
  page_1:
    display_options:
      title: "निगमित प्रशासन\r\n"
