display:
  default:
    display_options:
      title: 'हाइड्रो पावर'
  page_1:
    display_options:
      header:
        area:
          content:
            value: '<p>एसजेवीएन ने एकल जलविद्युत परियोजना कंपनी से प्रारंभ करके आज हिमाचल प्रदेश उत्‍तराखण्‍ड तथा पड़ोसी देशों नेपाल और भूटान में जलविद्युत परियोजनाओं के कार्यान्‍वयन में प्रवेश किया है।एसजेवीएन देश के सबसे बड़े 1500 मेगावाट के नाथपा झाकड़ी ज‍लविद्युत स्‍टेशन का सफलतापूर्वक प्रचालन कर रहा है तथा भूमिगत टरबाईनों के हिस्‍सों में सिल्‍ट क्षरण की समस्‍या से निपटने के पश्‍चात वर्ष-दर-वर्ष विद्युत उत्‍पादन और रखरखाव में नए बेंचमार्क स्‍थापित कर रहा है।</p>'
            format: full_html
  page_2:
    display_options:
      header:
        area:
          content:
            value: '<p>देश की जलविद्युत क्षमता का दोहन करने में प्राप्त अनुभव के बाद, एसजेवीएन ने थर्मल पावर के उत्पादन में कदम रखा। निष्पादन के लिए शुरू की गई पहली परियोजना जिले में 1320 मेगावाट क्षमता का बक्सर थर्मल पावर प्लांट है। एसजेवीएन ने 04.07.2013 को बक्सर बिजली कंपनी का अधिग्रहण किया और 17.10.2013 को इसका नाम बदलकर एसजेवीएन थर्मल प्राइवेट लिमिटेड कर दिया (एसजेवीएन लिमिटेड की पूर्ण स्वामित्व वाली सहायक कंपनी).</p>'
            format: full_html
      title: "ताप विद्युत\r\n"
  page_3:
    display_options:
      header:
        area:
          content:
            value: '<p>एसजेवीएन ने महाराष्‍ट्र में इसकी पहली परियोजना की कमीशनिंग के साथ पवन विद्युत उत्‍पादन में विविधीकरण किया है। महाराष्‍ट्र के अहमदनगर जिले में खिरवीरे तथा कोंभालने गांव में 47.6 मेगावाट की खिरवीरे पवन विद्युत परियोजना स्‍थापित की गई है। सभी 56 पवन विद्युत टरबाईनों से 85.65 मिलियन यूनिट वार्षिक अक्षय ऊर्जा उत्‍पादित होगी। प्रत्‍येक पवन विद्युत टरबाईन की 850 केवी ऊर्जा उत्‍पादित करने की क्षमता है। इन पवन ऊर्जा फार्म से उत्‍पादित विद्युत को 132 केवी पारेषण लाईन के माध्‍यम से अकोलेग्रिड सब-स्‍टेशन पर पूल किया जा रहा है। परियोजना का निष्‍पादन टर्नकी आधार पर किया गया है।</p>'
            format: full_html
      title: "पवन विद्युत\r\n"
  page_4:
    display_options:
      header:
        area:
          content:
            value: '<p>एसजेवीएन ने दिनांक 31.03.2017 को गुजरात के चारंका सौर पार्क में अपनी पहली परियोजना की कमीशनिंग के साथ सौर ऊर्जा उत्‍पादन में विविधीकरण किया है I आज की तारीख में, कुल 81.3 मेगावाट की स्थापित क्षमता वाली 3 सौर परियोजनाएं प्रचालन में हैं।</p>'
            format: full_html
      title: "सौर ऊर्जा\r\n"
  page_5:
    display_options:
      header:
        area:
          content:
            value: '<p>एक विद्युत उत्‍पादन कंपनी से एसजेवीएन ने अन्‍य कंपनियों के साथ भागीदारी में क्रॉस बार्डर इंडो-नेपाल पारेषण लाईन डालने के साथ विद्युत पारेषण के क्षेत्र में भी प्रवेश किया है। ट्रांसमिशन लाईन के भारतीय किनारे की ओर मुजफ्फरपुर से टीएलपी नेपाल कनेक्‍शन बिन्‍दु तक 128 कि.मी. लंबी टि्वन मूस 400 केवी की डी/सी लाईन की स्‍थापना के लिए इस उद्देश्‍य हेतु गठित क्रॉस बार्डर ट्रांसमिशन लाईन के भारतीय भाग (89 कि.मी. लंबी) के निष्‍पादन के लिए एसजेवीएन एक भागीदार तथा परामर्शक है। यह महत्‍वपूर्ण पारेषण लाईन नेपाल से भारत के लिए विद्युत निकासी में सहायता करेगी। यह लाईन नेपाल में 900 मेगावाट की अरुण-।।। परियोजना जिसे एसजेवीएन निष्‍पादित कर रहा है से विद्युत निकासी में भी सहायता करेगी।</p>'
            format: full_html
      title: "विद्युत पारेषण\r\n"
