display:
  default:
    display_options:
      title: 'हाइड्रो पावर'
  page_2:
    display_options:
      title: "ताप विद्युत\r\n"
  page_3:
    display_options:
      title: "पवन विद्युत\r\n"
  page_4:
    display_options:
      title: "सौर ऊर्जा\r\n"
  page_5:
    display_options:
      title: "विद्युत पारेषण\r\n"
