<?php

use Drupal\file\Entity\File;
function flip_preprocess_page(&$variables){
    $config = \Drupal::config('config.flipbook_chooseconfig');
    $choice_value = $config->get('pdf.choice');    
    global $base_url;
    $host = $base_url;
    $object = $variables['element']['#object'];
    $typeLabel = $object->get('name')->getValue();
    $flipbook = $object->get('flipbook')->getValue();
    $flipdata = $flipbook[0]['target_id'];
    $file1 = File::load($flipdata);
    $url = (\Drupal::hasService('file_url_generator')) ? \Drupal::service('file_url_generator')->generateAbsoluteString($file1->getFileUri()) : file_url_transform_relative(($file1->getFileUri()));
    $variables['#attached']['drupalSettings']['pdfpath'][$flipdata] = $url;
    $flipimage = $object->get('flipbook_cover')->getValue()[0]['target_id'];
    $file = File::load($flipimage);
    $coverimageurl = (\Drupal::hasService('file_url_generator')) ? \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri()) : file_url_transform_relative(($file->getFileUri()));

    if($choice_value ==1)
    {
    $variables['#attached']['library'][] = 'flipbook/flipbook';
    }
    else
    {
     $variables['#attached']['library'][] = 'flipbook/flipbook_nopopup';   
    }
    $variables['#attached']['drupalSettings']['modulepath'] = \Drupal::service('extension.list.module')->getPath('flipbook');
    $variables['#attached']['drupalSettings']['pdfpath'] = $url;
    $variables['#attached']['drupalSettings']['pdfchoice'] = $choice_value;
    $variables['#attached']['drupalSettings']['host'] = $host;
    $variables['title'] = $typeLabel[0]['value'];
    $variables['bannercover'] = $coverimageurl;
    $variables['url'] = $url;
    $variables['pdfchoice']= $choice_value;
}

/**
 * Implements hook_theme()
 */
function flipbook_theme($existing, $type, $theme, $path) {
    return [
        'field__flipbook__flipbook__flipbook' => [
            'template' => 'flipbook',
            'preprocess functions' => ['flip_preprocess_page'],
        ],
        'views_view_field__field_flipbook' => [
            'template' => 'flipbook',
            'preprocess functions' => ['flip_preprocess_page'],
        ],
    ];
}
