display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        operations:
          label: कार्यवाही
      pager:
        options:
          tags:
            next: 'अगला ›'
            previous: '‹ पिछला'
  page_1:
    display_title: पृष्ठ
