<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\user\UserDataInterface;
use Drupal\user\UserInterface;


/**
 * Add callback for submit at user/{uid}/edit page
 */
function logout_after_password_change_form_user_form_alter(array &$form, FormStateInterface $form_state, $form_id): void
{
  $uid = \Drupal::currentUser()->id();
  /** @var UserDataInterface $userData */
  $userData = \Drupal::service('user.data');
  if ($userData->get('logout_after_password_change', $uid, 'is_password_reset')) {
    $form['actions']['submit']['#submit'][] = '_logout_after_password_change_logout';
    _logout_after_password_change_keep_just_password($form);
  }
}

/**
 * If password change, log out and redirect
 */
function _logout_after_password_change_logout(array &$form, FormStateInterface $form_state): void
{
  if ($form_state->getValue('pass')) {
    user_logout();
    $form_state->setRedirect('user.login', [], ['query' => ['logout' => 1]]);
  }
}

/**
 * Remove all fields and keep just password
 */
function _logout_after_password_change_keep_just_password(array &$form): void
{
  foreach(array_keys($form) as $array_key) {
    if (str_starts_with($array_key, '#') or $array_key === 'actions' or str_starts_with($array_key, 'form_')) {
      continue;
    }
    elseif ($array_key === 'account') {
      foreach(array_keys($form[$array_key]) as $account_key) {
        if (str_starts_with($account_key, '#') or $account_key === 'pass') {
          continue;
        }
        $form[$array_key][$account_key]['#access'] = FALSE;
      }
      continue;
    }
    $form[$array_key]['#access'] = FALSE;
  }
}

/**
 * Save to user session that the user was logged in by password reset link
 */
function logout_after_password_change_form_user_pass_reset_alter(array &$form, FormStateInterface &$form_state): void
{
  /* @var $user UserInterface */
  $user = $form_state->getBuildInfo()['args'][0];
  $uid = $user->id();
  /** @var UserDataInterface $userData */
  $userData = \Drupal::service('user.data');
  $userData->set('logout_after_password_change', $uid,'is_password_reset', true);
}

/**
 * Delete user data when logged out
 */
function logout_after_password_change_user_logout(AccountInterface $account): void
{
  $uid = $account->id();
  $userData = \Drupal::service('user.data');
  $userData->delete('logout_after_password_change', $uid, 'is_password_reset');
}
